runtime: php55
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html

 - url: /(.+\.php)$
    script: \1

  - url: /(.*)
    static_files: www/\1
    upload: www/(.*)
